# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('html', models.TextField(blank=True, help_text='HTML Code')),
            ],
        ),
    ]
