# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_htmlpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='description_tag',
            field=models.CharField(default='title', max_length=156),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htmlpage',
            name='title_tag',
            field=models.CharField(default='description', max_length=47),
            preserve_default=False,
        ),
    ]
