# Generated by Django 4.2.7 on 2023-11-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20161007_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlpage',
            old_name='html',
            new_name='content',
        ),
    ]
