# Generated by Django 4.2.7 on 2023-11-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_html_htmlpage_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HtmlPage',
            new_name='Page',
        ),
    ]
